import {
  chunkCoordinate,
  chunkKey,
  createChunkCircle,
  type ChunkCoordinate,
  type ChunkMeshBuffers,
  type VoxelChunk,
} from "./chunk-types";
import type { TerrainWorker } from "./terrain-worker";
import type { VoxelWorld } from "./world";
import type { VoxelWorldRenderer } from "./world-renderer";

export interface ChunkStreamerOptions {
  world: VoxelWorld;
  renderer: VoxelWorldRenderer;
  worker: TerrainWorker;
  viewDistance: number;
  unloadMargin?: number;
  maxConcurrent?: number;
  maxMeshConcurrency?: number;
  meshBudgetMs?: number;
  /** Chunks within this radius must be loaded before the world reports ready. */
  readyRadius?: number;
  onChunkCountChanged?: () => void;
  onGeometryChanged?: () => void;
}

// All eight surrounding chunks. Diagonals matter too: AO and light sampling at
// chunk corners reads diagonal blocks, so missing them left lit seams.
const NEIGHBOR_OFFSETS: readonly ChunkCoordinate[] = [
  { x: 1, z: 0 },
  { x: -1, z: 0 },
  { x: 0, z: 1 },
  { x: 0, z: -1 },
  { x: 1, z: 1 },
  { x: 1, z: -1 },
  { x: -1, z: 1 },
  { x: -1, z: -1 },
];

const distanceSquared = (a: ChunkCoordinate, b: ChunkCoordinate): number => {
  const dx = a.x - b.x;
  const dz = a.z - b.z;
  return dx * dx + dz * dz;
};

const parseChunkKey = (key: string): ChunkCoordinate => {
  const [x, z] = key.split(",").map(Number);
  return { x, z };
};

const now = (): number => (typeof performance !== "undefined" ? performance.now() : Date.now());

/**
 * Streams terrain chunks around the player. Missing chunks are generated by a
 * worker pool nearest-first, meshed off the main thread, and uploaded to the GPU
 * under a per-frame time budget so a large view distance stays responsive.
 * Player edits are kept in `VoxelWorld` while a chunk is out of range.
 */
export class ChunkStreamer {
  private readonly loaded = new Set<string>();
  private readonly pendingGenerate = new Set<string>();
  private readonly queued = new Set<string>();
  private readonly meshInFlight = new Set<string>();
  private readonly meshQueued = new Set<string>();
  private readonly meshDirty = new Set<string>();
  private readonly pendingMeshes = new Map<string, ChunkMeshBuffers>();
  private queue: ChunkCoordinate[] = [];
  private center: ChunkCoordinate | null = null;
  private version = 0;
  private disposed = false;
  private ready = false;
  private initial: Set<string> | null = null;
  private readyResolve: (() => void) | null = null;
  private readyPromise: Promise<void>;

  public constructor(private readonly options: ChunkStreamerOptions) {
    this.readyPromise = new Promise((resolve) => {
      this.readyResolve = resolve;
    });
  }

  public get isReady(): boolean {
    return this.ready;
  }

  public whenReady(): Promise<void> {
    return this.readyPromise;
  }

  /** Fraction of the startup radius that has loaded, for the boot screen. */
  public get loadProgress(): number {
    if (!this.initial || this.initial.size === 0) {
      return 0;
    }
    let loaded = 0;
    for (const key of this.initial) {
      if (this.loaded.has(key)) {
        loaded += 1;
      }
    }
    return loaded / this.initial.size;
  }

  public reset(): void {
    this.version += 1;
    this.loaded.clear();
    this.pendingGenerate.clear();
    this.queued.clear();
    this.meshInFlight.clear();
    this.meshQueued.clear();
    this.meshDirty.clear();
    this.pendingMeshes.clear();
    this.queue = [];
    this.center = null;
    this.ready = false;
    this.initial = null;
    this.readyPromise = new Promise((resolve) => {
      this.readyResolve = resolve;
    });
  }

  public dispose(): void {
    this.disposed = true;
    this.version += 1;
    this.loaded.clear();
    this.pendingGenerate.clear();
    this.queued.clear();
    this.meshInFlight.clear();
    this.meshQueued.clear();
    this.meshDirty.clear();
    this.pendingMeshes.clear();
    this.queue = [];
    this.center = null;
    this.ready = false;
    this.initial = null;
    this.readyResolve = null;
  }

  public update(position: { x: number; z: number }): void {
    if (this.disposed) {
      return;
    }

    const next: ChunkCoordinate = {
      x: chunkCoordinate(position.x),
      z: chunkCoordinate(position.z),
    };

    if (!this.center || this.center.x !== next.x || this.center.z !== next.z) {
      this.center = next;
      this.refreshDesired();
    }

    this.drainDirtyChunks();
    this.pump();
    this.pumpMeshes();
    this.uploadPendingMeshes();
  }

  /** Re-meshes chunks flagged as dirty by `VoxelWorld` edits. */
  private drainDirtyChunks(): void {
    const dirty = this.options.world.consumeDirtyChunks();
    for (const coordinate of dirty) {
      // Relight and re-mesh the 3x3 chunk neighborhood so propagated sky and
      // block light stays correct across the edited chunk's borders.
      for (let dx = -1; dx <= 1; dx += 1) {
        for (let dz = -1; dz <= 1; dz += 1) {
          this.requestMesh({ x: coordinate.x + dx, z: coordinate.z + dz });
        }
      }
    }
  }

  private refreshDesired(): void {
    const center = this.center;
    if (!center) {
      return;
    }

    const viewDistance = this.options.viewDistance;
    const desired = createChunkCircle(center, viewDistance);
    const desiredKeys = new Set(desired.map(chunkKey));
    if (!this.initial) {
      const readyRadius = Math.min(viewDistance, this.options.readyRadius ?? 3);
      this.initial = new Set(createChunkCircle(center, readyRadius).map(chunkKey));
    }

    const unloadDistance = viewDistance + (this.options.unloadMargin ?? 1);
    const unloadSquared = unloadDistance * unloadDistance;
    for (const key of [...this.loaded]) {
      if (distanceSquared(parseChunkKey(key), center) > unloadSquared) {
        this.unloadChunk(parseChunkKey(key));
      }
    }

    this.queue = this.queue.filter((coordinate) => desiredKeys.has(chunkKey(coordinate)));
    this.queued.clear();
    for (const coordinate of this.queue) {
      this.queued.add(chunkKey(coordinate));
    }

    const missing = desired
      .filter((coordinate) => {
        const key = chunkKey(coordinate);
        return !this.loaded.has(key) && !this.pendingGenerate.has(key) && !this.queued.has(key);
      })
      .sort((a, b) => distanceSquared(a, center) - distanceSquared(b, center));

    for (const coordinate of missing) {
      this.queue.push(coordinate);
      this.queued.add(chunkKey(coordinate));
    }
  }

  private pump(): void {
    const maxConcurrent = this.options.maxConcurrent ?? 16;
    while (this.pendingGenerate.size < maxConcurrent && this.queue.length > 0) {
      const coordinate = this.queue.shift();
      if (!coordinate) {
        break;
      }
      this.queued.delete(chunkKey(coordinate));
      this.generateChunk(coordinate);
    }
  }

  private generateChunk(coordinate: ChunkCoordinate): void {
    const version = this.version;
    const stored = this.options.world.getEditedChunk(coordinate);
    if (stored) {
      this.commit(coordinate, stored, version);
      return;
    }

    const key = chunkKey(coordinate);
    this.pendingGenerate.add(key);
    this.options.worker.generate(coordinate).then(
      (chunk) => {
        this.pendingGenerate.delete(key);
        this.commit(coordinate, chunk, version);
        this.pump();
      },
      () => {
        this.pendingGenerate.delete(key);
        this.pump();
      },
    );
  }

  private commit(coordinate: ChunkCoordinate, chunk: VoxelChunk, version: number): void {
    if (this.disposed || version !== this.version || !this.isWithinUnload(coordinate)) {
      return;
    }

    this.options.world.setChunk(chunk);
    this.loaded.add(chunkKey(coordinate));
    this.options.onChunkCountChanged?.();
    this.checkReady();

    this.requestMesh(coordinate);
    for (const offset of NEIGHBOR_OFFSETS) {
      this.requestMesh({ x: coordinate.x + offset.x, z: coordinate.z + offset.z });
    }
  }

  private requestMesh(coordinate: ChunkCoordinate): void {
    const key = chunkKey(coordinate);
    if (!this.loaded.has(key)) {
      return;
    }
    if (this.meshInFlight.has(key)) {
      this.meshDirty.add(key);
      return;
    }
    this.meshQueued.add(key);
  }

  /**
   * Starts meshing for queued chunks. Neighbor blocks are read when a job
   * actually starts, so a chunk that commits early is coalesced with the
   * neighbors that arrive in the same burst instead of being meshed repeatedly.
   */
  private pumpMeshes(): void {
    const maxConcurrency = this.options.maxMeshConcurrency ?? 6;
    const center = this.center;
    while (this.meshInFlight.size < maxConcurrency && this.meshQueued.size > 0) {
      let chosen: string | null = null;
      let chosenDistance = Number.POSITIVE_INFINITY;
      for (const key of this.meshQueued) {
        const distance = center ? distanceSquared(parseChunkKey(key), center) : 0;
        if (distance < chosenDistance) {
          chosen = key;
          chosenDistance = distance;
        }
      }
      if (!chosen) {
        break;
      }
      const chosenKey = chosen;
      this.meshQueued.delete(chosenKey);

      const coordinate = parseChunkKey(chosenKey);
      const chunk = this.options.world.getChunk(coordinate);
      if (!chunk || !this.loaded.has(chosenKey)) {
        continue;
      }

      const version = this.version;
      this.meshInFlight.add(chosenKey);
      const neighbors = new Map<string, Uint8Array>();
      for (let dx = -1; dx <= 1; dx += 1) {
        for (let dz = -1; dz <= 1; dz += 1) {
          if (dx === 0 && dz === 0) {
            continue;
          }
          const neighbor = this.options.world.getChunk({
            x: coordinate.x + dx,
            z: coordinate.z + dz,
          });
          if (neighbor) {
            neighbors.set(`${dx},${dz}`, neighbor.blocks);
          }
        }
      }
      this.options.worker.mesh(coordinate, chunk.blocks, neighbors).then(
        (mesh) => {
          this.meshInFlight.delete(chosenKey);
          if (this.disposed || version !== this.version || !this.loaded.has(chosenKey)) {
            return;
          }
          if (this.meshDirty.delete(chosenKey)) {
            this.requestMesh(coordinate);
            return;
          }
          this.pendingMeshes.set(chosenKey, mesh);
        },
        () => {
          this.meshInFlight.delete(chosenKey);
        },
      );
    }
  }

  private uploadPendingMeshes(): void {
    if (this.pendingMeshes.size === 0) {
      return;
    }

    const center = this.center;
    const entries: {
      key: string;
      coordinate: ChunkCoordinate;
      mesh: ChunkMeshBuffers;
      d: number;
    }[] = [];
    for (const [key, mesh] of this.pendingMeshes) {
      if (!this.loaded.has(key)) {
        this.pendingMeshes.delete(key);
        continue;
      }
      const coordinate = parseChunkKey(key);
      entries.push({
        key,
        coordinate,
        mesh,
        d: center ? distanceSquared(coordinate, center) : 0,
      });
    }
    entries.sort((a, b) => a.d - b.d);

    const budget = this.options.meshBudgetMs ?? 6;
    const start = now();
    for (const entry of entries) {
      this.pendingMeshes.delete(entry.key);
      this.options.renderer.applyMesh(entry.coordinate, entry.mesh);
      this.options.onGeometryChanged?.();
      if (now() - start >= budget) {
        break;
      }
    }
  }

  private unloadChunk(coordinate: ChunkCoordinate): void {
    const key = chunkKey(coordinate);
    this.loaded.delete(key);
    this.meshDirty.delete(key);
    this.meshQueued.delete(key);
    this.pendingMeshes.delete(key);
    if (!this.options.world.removeChunk(coordinate)) {
      return;
    }

    this.options.renderer.removeChunk(coordinate);
    for (const offset of NEIGHBOR_OFFSETS) {
      this.requestMesh({ x: coordinate.x + offset.x, z: coordinate.z + offset.z });
    }
    this.options.onChunkCountChanged?.();
    this.options.onGeometryChanged?.();
  }

  private isWithinUnload(coordinate: ChunkCoordinate): boolean {
    const center = this.center;
    if (!center) {
      return false;
    }
    const unloadDistance = this.options.viewDistance + (this.options.unloadMargin ?? 1);
    return distanceSquared(coordinate, center) <= unloadDistance * unloadDistance;
  }

  private checkReady(): void {
    if (this.ready || !this.initial) {
      return;
    }
    for (const key of this.initial) {
      if (!this.loaded.has(key)) {
        return;
      }
    }
    this.ready = true;
    this.readyResolve?.();
    this.readyResolve = null;
  }
}
